//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

class GL_OctreeRenderer : MonoBehaviour
{

	private static Material lineMaterial;

    public bool enabled = true;
    public bool RenderObstacle = true;
    public bool RenderEmpty = true;
    public bool RenderNonEmpty = true;
	public BoundsOctree boundsOctree;
	public static void CreateLineMaterial() 
	{
		if( !lineMaterial ) {
			lineMaterial = new Material( "Shader \"Lines/Colored Blended\" {" +
			                            "SubShader { Pass { " +
			                            "    Blend SrcAlpha OneMinusSrcAlpha " +
			                            "    ZWrite Off Cull Off Fog { Mode Off } " +
			                            "    BindChannels {" +
			                            "      Bind \"vertex\", vertex Bind \"color\", color }" +
			                            "} } }" );
			lineMaterial.hideFlags = HideFlags.HideAndDontSave;
			lineMaterial.shader.hideFlags = HideFlags.HideAndDontSave;
		}
	}
	public static GL_OctreeRenderer OctreeRenderer;

	public void Awake()
	{
		OctreeRenderer = this;
		CreateLineMaterial();
		
	}
	public void OnPostRender() {


        if (enabled)
        {
            lineMaterial.SetPass(0);
            GL.Begin(GL.LINES);

            boundsOctree.GL_Draw(false,RenderEmpty,false);
            boundsOctree.GL_Draw(false,false,RenderNonEmpty);
            boundsOctree.GL_Draw(RenderObstacle,false,false);

            GL.End();
        }	
		
	}
    public void OnGUI()
    {
        if (GUI.Button(new Rect(10, 40, 200, 18), "GL: "+enabled.ToString()))
        {
            enabled = !enabled;
        }
        if (enabled)
        {
            if (GUI.Button(new Rect(10, 62, 200, 18), "Obstacle Render: " + RenderObstacle.ToString()))
            {
                RenderObstacle = !RenderObstacle;
            }
            if (GUI.Button(new Rect(10, 84, 200, 18), "Empty Render: " + RenderEmpty.ToString()))
            {
                RenderEmpty = !RenderEmpty;
            }
            if (GUI.Button(new Rect(10, 108, 200, 18), "Environment Render: " + RenderNonEmpty.ToString()))
            {
                RenderNonEmpty = !RenderNonEmpty;
            }
        }
       
    }
}
